Using 16bit native Automatic Mixed Precision (AMP)
D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\loops\utilities.py:91: PossibleUserWarning: `max_epochs` was not set. Setting it to 1000 epochs. To train without an epoch limit, set `max_epochs=-1`.
  rank_zero_warn(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:133: UserWarning: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
  rank_zero_warn("You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "D:\conda\envs\NLP_Translator_39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\utilities\seed.py", line 154, in isolate_rng
    yield
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1126, in tune
    result = self.tuner._tune(
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\tuner\tuning.py", line 63, in _tune
    result["lr_find"] = lr_find(self.trainer, model, **lr_find_kwargs)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\tuner\lr_finder.py", line 224, in lr_find
    trainer.tuner._run(model)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\tuner\tuning.py", line 73, in _run
    self.trainer._run(*args, **kwargs)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1234, in _run
    results = self._run_stage()
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1351, in _run_train
    self.fit_loop.run()
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 268, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 171, in advance
    batch = next(data_fetcher)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 184, in __next__
    return self.fetching_function()
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 259, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 273, in _fetch_next_batch
    batch = next(iterator)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 553, in __next__
    return self.request_next_batch(self.loader_iters)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 565, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\conda\envs\NLP_Translator_39\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\project\kang_bart\dataload\dataset.py", line 23, in __getitem__
    masked_input = TextInfilling(tokenized_input, mask_token_id=self.tokenizer.mask_token_id).mask()
  File "D:\project\kang_bart\utils\text_infilling.py", line 11, in __init__
    self.span = self.get_span()
  File "D:\project\kang_bart\utils\text_infilling.py", line 32, in get_span
    span = np.random.choice(self.n, p=self.probabilities)
  File "mtrand.pyx", line 939, in numpy.random.mtrand.RandomState.choice
